cci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,6 +18,16 @@ jobs:
     # See: https://circleci.com/docs/2.0/configuration-reference/#steps
     steps:
       - checkout
+
+      - restore_cache:
+          keys:
+            - maven-{{ checksum "pom.xml" }}
+
+      - run:
+          name: "build project"
+          command: |
+            mvn clean install
+
       - run:
           name: "prepare aio"
           command: |
@@ -39,44 +49,49 @@ jobs:
             aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key  private.key --file
             
             aio auth login --ctx=aio-cli-plugin-cloudmanager > login.log
-
-
-#      - run:
-#          name: "reset the RDE"
-#          command: |
-#                @aio aem:rde:reset
-
-      - restore_cache:
-          keys:
-            - maven-{{ checksum "pom.xml" }}
-
+            
       - run:
-          name: "build project"
-          command: |
-            mvn clean package
-
-      - run:
-          name: "install on RDE"
+          name: "Configure the RDE coordinates"
           command: |
             aio config:set cloudmanager_orgid  "${SERVICE_ACCOUNT_ORG_ID}"
             aio config:set cloudmanager_programid "${PROGRAM_ID}" 
             aio config:set cloudmanager_environmentid "${ENVIRONMENT_ID}"
+
+      - run:
+          name: "reset the RDE"
+          command: |
+                aio aem:rde:reset
+
+      - run:
+          name: "setup new admin user on RDE"
+          command: |
+            # Note: I have observed some install failures if the user/password contain special characters like "+"
+            # this is currently being investigated: SKYOPS-52856
+            .circleci/create-user-osgi-cfg.sh -u "${AUTHOR_USER}" -p "${AUTHOR_PASSWORD}" -q true
             
+            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add.cfg.json
+            
+            # delete the osgi config, this is fine since the script contained within the config is not reverterd
+            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add
+
+      - run:
+          name: "install project on RDE"
+          command: |
             ALL_FILE=$(ls all/target/ | grep zip ) && aio aem:rde:install -t content-package "all/target/${ALL_FILE}"
             DISP_FILE=$(ls dispatcher/target/ | grep zip ) && aio aem:rde:install -t dispatcher-config "dispatcher/target/${DISP_FILE}"
 
       - run:
-          name: "Run Integration Tests"
+          name: "Run Local Integration Tests"
           command: |
             cd it.tests 
             mvn clean verify \
             -Plocal \
             -Dit.author.url="${AUTHOR_URL}" \
-            -Dit.author.user="${AUTHOR_USER}" \
-            -Dit.author.password="${AUTHOR_PASSWORD}" \
+            -Dit.author.user="${AEM_USER}" \
+            -Dit.author.password="${AEM_PASSWORD}" \
             -Dit.publish.url="${PUBLISH_URL}" \
-            -Dit.publish.user="${PUBLISH_USER}" \
-            -Dit.publish.password="${PUBLISH_PASSWORD}" \
+            -Dit.publish.user="${AEM_USER}" \
+            -Dit.publish.password="${AEM_PASSWORD}" \
             -Dmaven.javadoc.skip=true \
             -Dmaven.surefire.debug
 
@@ -85,30 +100,24 @@ jobs:
           paths:
             - /home/circleci/.m2/repository/
 
-  eaas:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
-    docker:
-      - image: cimg/openjdk:11.0-node
-    steps:
-      - checkout
       - run:
           name: "download Eaas cli"
           command: |
             curl -L https://github.com/andresbott/aem-guides-wknd/releases/download/poc-eaas/eaas-0.4.4  --output eaas
             chmod +x ./eaas
             sudo mv ./eaas /usr/local/bin/eaas
+
       - run:
           name: "Eaas login"
           command: |
-              echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
-              eaas --url="https://devxapi.adobe.io" login integration  \
-                --organization "${SERVICE_ACCOUNT_ORG_ID}" \
-                --clientId "${SERVICE_ACCOUNT_CLIENT_ID}" \
-                --secret "${SERVICE_ACCOUNT_CLIENT_SECRET}" \
-                --privateKey private.key \
-                --accountId "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"            
-              eaas health
+            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
+            eaas --url="https://devxapi.adobe.io" login integration  \
+              --organization "${SERVICE_ACCOUNT_ORG_ID}" \
+              --clientId "${SERVICE_ACCOUNT_CLIENT_ID}" \
+              --secret "${SERVICE_ACCOUNT_CLIENT_SECRET}" \
+              --privateKey private.key \
+              --accountId "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"            
+            eaas health
       - run:
           name: "Generate the IT payload"
           command: |
@@ -124,41 +133,49 @@ jobs:
       - run:
           name: "Run the IT task"
           command: |
-              # Start the IT Task            
-              eaas start it-task -f it-task-payload.json | tee it-task.out
-              task_id="`cat it-task.out | grep "Id:" | awk -F':' '{print $2}' | xargs`"
-              if [[ "${task_id}" == "" ]]; then
-                  echo "EAAS failed to generate task_id"
-                  exit 1
+            # Start the IT Task            
+            eaas start it-task -f it-task-payload.json | tee it-task.out
+            task_id="`cat it-task.out | grep "Id:" | awk -F':' '{print $2}' | xargs`"
+            if [[ "${task_id}" == "" ]]; then
+                echo "EAAS failed to generate task_id"
+                exit 1
+            fi
+            
+            # Check IT Task status
+            start_time="`date +%s`"
+            IT_TASK_TIMEOUT=900
+            status_file="taskId-${task_id}.status"
+            while true; do
+              eaas status it-task --taskId ${task_id} | tee "${status_file}"
+              test_status="`cat "${status_file}" | grep "Status:" | awk -F':' '{print $2}' | xargs `"
+              if [[ "${test_status}" == "terminated" || "${test_status}" == "failed" || $((`date +%s` - ${start_time})) -gt ${IT_TASK_TIMEOUT} ]]; then
+                break
               fi
+            echo "waiting 10s to check again for task status"
+            sleep 10
+            done
             
-              # Check IT Task status
-              start_time="`date +%s`"
-              IT_TASK_TIMEOUT=900
-              status_file="taskId-${task_id}.status"
-              while true; do
-                eaas status it-task --taskId ${task_id} | tee "${status_file}"
-                test_status="`cat "${status_file}" | grep "Status:" | awk -F':' '{print $2}' | xargs `"
-                if [[ "${test_status}" == "terminated" || "${test_status}" == "failed" || $((`date +%s` - ${start_time})) -gt ${IT_TASK_TIMEOUT} ]]; then
-                  break
-                fi
-              echo "waiting 10s to check again for task status"
-              sleep 10
-              done
+            # parse results
+            test_passed="`cat "${status_file}" | grep "Tests passed:" | awk -F':' '{print $2}' | xargs `"
+            echo ${task_id}
+            echo ${test_status} 
+            echo ${test_passed} 
             
-              # parse results
-              test_passed="`cat "${status_file}" | grep "Tests passed:" | awk -F':' '{print $2}' | xargs `"
-              echo ${task_id}
-              echo ${test_status} 
-              echo ${test_passed} 
-        
-              # Generate task exit code
-              if [[ "${test_passed}" == "true" ]]; then exit 0; else exit 1; fi            
+            # Generate task exit code
+            if [[ "${test_passed}" == "true" ]]; then exit 0; else exit 1; fi           
             
+
+      - run:
+          name: Uninstall the user from the RDE
+          command: |
+            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove.cfg.json
+            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove
+          when: always
+
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
 workflows:
   pr-verify:
     jobs:
-      - eaas
+      - verify
