cci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -323,7 +323,77 @@ jobs:
             -Dit.publish.user="${AEM_USER}" \
             -Dit.publish.password="${AEM_PASSWORD}" \
             -Dmaven.javadoc.skip=true \
-            -Dmaven.surefire.debug            
+            -Dmaven.surefire.debug
+
+  Product-tests:
+    docker:
+      - image: cimg/openjdk:11.0-node
+    steps:
+      - run:
+          name: "download Eaas cli"
+          command: |
+            curl -L https://github.com/andresbott/aem-guides-wknd/releases/download/poc-eaas/eaas-0.4.4  --output eaas
+            chmod +x ./eaas
+            sudo mv ./eaas /usr/local/bin/eaas
+
+      - run:
+          name: "Eaas login"
+          command: |
+            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
+            eaas --url="https://devxapi.adobe.io" login integration  \
+              --organization "${SERVICE_ACCOUNT_ORG_ID}" \
+              --clientId "${SERVICE_ACCOUNT_CLIENT_ID}" \
+              --secret "${SERVICE_ACCOUNT_CLIENT_SECRET}" \
+              --privateKey private.key \
+              --accountId "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"            
+            eaas health
+      - run:
+          name: "Generate the IT payload"
+          command: |
+            eaas generate it-task-payload
+            
+            sed -i "s|groupId:test-module-artifactId:version|com.adobe.cq.cloud:com.adobe.cq.cloud.testing.it.smoke:0.14.8-4f7653d|g ;
+            s|https:\/\/author-skyline:port|${AUTHOR_URL}|g ;
+            s|https:\/\/publish-skyline:port|${PUBLISH_URL}|g ;
+            s/authorPV\\$\\$/${AEM_PASSWORD}/g ;
+            s/publishPV\\$\\$/${AEM_PASSWORD}/g ;
+            s/user\":\ \"admin/user\": \"${AEM_USER}/g ;
+            " it-task-payload.json            
+
+      - run:
+          name: "Run the IT task"
+          command: |
+            # Start the IT Task            
+            eaas start it-task -f it-task-payload.json | tee it-task.out
+            task_id="`cat it-task.out | grep "Id:" | awk -F':' '{print $2}' | xargs`"
+            if [[ "${task_id}" == "" ]]; then
+                echo "EAAS failed to generate task_id"
+                exit 1
+            fi
+            
+            # Check IT Task status
+            start_time="`date +%s`"
+            IT_TASK_TIMEOUT=900
+            status_file="taskId-${task_id}.status"
+            while true; do
+              eaas status it-task --taskId ${task_id} | tee "${status_file}"
+              test_status="`cat "${status_file}" | grep "Status:" | awk -F':' '{print $2}' | xargs `"
+              if [[ "${test_status}" == "terminated" || "${test_status}" == "failed" || $((`date +%s` - ${start_time})) -gt ${IT_TASK_TIMEOUT} ]]; then
+                break
+              fi
+            echo "waiting 10s to check again for task status"
+            sleep 10
+            done
+            
+            # parse results
+            test_passed="`cat "${status_file}" | grep "Tests passed:" | awk -F':' '{print $2}' | xargs `"
+            echo ${task_id}
+            echo ${test_status} 
+            echo ${test_passed} 
+            
+            # Generate task exit code
+            if [[ "${test_passed}" == "true" ]]; then exit 0; else exit 1; fi           
+      
 
 
 # Invoke jobs via workflows
@@ -331,11 +401,16 @@ jobs:
 workflows:
   PR-validation:
     jobs:
-#      - Build
+      - Build
 #      - RDE-reset
-#      - RDE-install:
-#          requires:
-#            - Build
+      - RDE-install:
+          requires:
+            - Build
 #            - RDE-reset
 
-      - Customer-ITs
+      - Customer-ITs:
+          requires:
+            - RDE-install
+      - Product-tests:
+          requires:
+            - RDE-install
